services:
  db:
    image: postgres:16-alpine
    container_name: kuber_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kuber
      POSTGRES_USER: kuber
      POSTGRES_PASSWORD: kuber
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kuber -d kuber"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: kuber_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: kuber_web
    command: gunicorn kuber.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - .:/code

volumes:
  pg_data:
