# Generated by Django 5.2.3 on 2025-06-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_variablecategory_variableparameter_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expression', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constants', to='core.algolist')),
            ],
        ),
    ]
