# Generated by Django 5.2.3 on 2025-07-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uservariable_delete_userdefinedconstant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVariable',
            new_name='UserDefinedVariable',
        ),
    ]
