# Generated by Django 5.2.3 on 2025-08-03 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_uservariable_userdefinedvariable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='value',
            new_name='lhs_variable',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='variable_name',
        ),
        migrations.AddField(
            model_name='condition',
            name='lhs_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='condition',
            name='rhs_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='condition',
            name='rhs_type',
            field=models.CharField(choices=[('value', 'Value'), ('variable', 'Variable')], default=datetime.datetime(2025, 8, 3, 7, 15, 44, 274062, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='rhs_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='rhs_variable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '=='), ('!=', '!=')], max_length=10),
        ),
    ]
