# Generated by Django 5.2.3 on 2025-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_value_condition_lhs_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='function_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
