# Generated by Django 5.2.3 on 2025-08-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_variable_function_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('broker_username', models.CharField(max_length=255)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlgoBrokerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('hedge', 'Hedge'), ('paper', 'Paper')], default='primary', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.algorithmlogic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brokeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(blank=True, null=True)),
                ('dtype', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('json', 'JSON')], default='text', max_length=20)),
                ('algo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.algorithmlogic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['user', 'broker'], name='core_broker_user_id_8644e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokeraccount',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='uniq_brokeraccount_label_per_user'),
        ),
        migrations.AddConstraint(
            model_name='brokeraccount',
            constraint=models.UniqueConstraint(fields=('user', 'broker', 'broker_username'), name='uniq_real_account_per_user_broker'),
        ),
        migrations.AddIndex(
            model_name='algobrokerlink',
            index=models.Index(fields=['user', 'algo'], name='core_algobr_user_id_d73b44_idx'),
        ),
        migrations.AddConstraint(
            model_name='algobrokerlink',
            constraint=models.UniqueConstraint(fields=('user', 'algo', 'account'), name='uniq_link_per_user_algo_account'),
        ),
        migrations.AddConstraint(
            model_name='algobrokerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'algo'), name='uniq_default_account_per_user_algo'),
        ),
        migrations.AddConstraint(
            model_name='globalvariable',
            constraint=models.UniqueConstraint(fields=('key', 'algo', 'user'), name='uniq_global_key_scope'),
        ),
    ]
