# Generated by Django 5.2.3 on 2025-08-10 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brokeraccount_algobrokerlink_globalvariable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], default='paper', max_length=10)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error')], default='stopped', max_length=10)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brokeraccount')),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.algorithmlogic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'algo', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='AlgoStatusStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('unregistered', 'Unregistered'), ('paper_ready', 'Paper Ready'), ('live_ready', 'Live Ready'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('error', 'Error')], max_length=24)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('bulma_tag_class', models.CharField(blank=True, default='', max_length=64)),
                ('bulma_bg_class', models.CharField(blank=True, default='', max_length=64)),
                ('dot_hex', models.CharField(blank=True, default='', max_length=7)),
                ('text_hex', models.CharField(blank=True, default='', max_length=7)),
                ('order', models.PositiveIntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'key'],
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DailyPnl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], max_length=10)),
                ('date', models.DateField()),
                ('pnl', models.FloatField(default=0.0)),
                ('cum_pnl', models.FloatField(default=0.0)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.algorithmlogic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'algo', 'mode', 'date'], name='core_dailyp_user_id_6c6e5d_idx')],
                'unique_together': {('user', 'algo', 'mode', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], max_length=10)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.algorithmlogic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'algo', 'mode', '-ts'], name='core_execut_user_id_2dc2c1_idx')],
            },
        ),
    ]
