# Generated by Django 5.2.3 on 2025-08-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_algorun_algostatusstyle_dailypnl_executionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='adapter_path',
            field=models.CharField(blank=True, help_text='Import path to adapter class, e.g. core.services.brokers.zerodha.ZerodhaClient', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variableparameter',
            name='allowed_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
