# Generated by Django 5.2.3 on 2025-08-16 20:50

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_broker_adapter_path_variable_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('total_minor', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlgoOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_pct', models.PositiveIntegerField(default=15, help_text='Platform share % of net(after discounts)')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='unlisted', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('max_subs', models.PositiveIntegerField(blank=True, help_text='Cap subscribers; blank = no cap', null=True)),
                ('allow_trial', models.BooleanField(default=True)),
                ('default_trial_days', models.PositiveIntegerField(default=7)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('preview_stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.algolist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlgoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=100)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('price_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('trial_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_plan_id', models.CharField(blank=True, max_length=80)),
                ('stripe_price_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.algooffer')),
            ],
        ),
        migrations.CreateModel(
            name='AlgoInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(default=core.models.invite_token, editable=False, max_length=64, unique=True)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount'), ('none', 'None')], default='none', max_length=10)),
                ('discount_val', models.PositiveIntegerField(default=0, help_text='percent (0-100) or minor amount')),
                ('trial_days', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.algooffer')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.algoplan')),
            ],
        ),
        migrations.CreateModel(
            name='AlgoSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('payment_provider', models.CharField(blank=True, max_length=20)),
                ('provider_cust_id', models.CharField(blank=True, max_length=64)),
                ('provider_sub_id', models.CharField(blank=True, max_length=64)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.algoinvitation')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.algooffer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.algoplan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algo_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HiddenAlgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.algolist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('gross_minor', models.PositiveIntegerField()),
                ('discount_minor', models.PositiveIntegerField(default=0)),
                ('net_minor', models.PositiveIntegerField()),
                ('platform_fee_pct', models.PositiveIntegerField(default=15)),
                ('platform_fee_minor', models.PositiveIntegerField(default=0)),
                ('creator_gross_minor', models.PositiveIntegerField(default=0)),
                ('gst_pct', models.PositiveIntegerField(default=18)),
                ('gst_minor', models.PositiveIntegerField(default=0)),
                ('tds_pct', models.PositiveIntegerField(default=0)),
                ('tds_minor', models.PositiveIntegerField(default=0)),
                ('creator_payout_minor', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='paid', max_length=12)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.algooffer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.algosubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_earnings', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.algooffer')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('bank_ac_no', models.CharField(blank=True, max_length=50)),
                ('pan', models.CharField(blank=True, max_length=15)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'received_at'], name='core_webhoo_provide_0330d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlgoEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='subscription', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.algolist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'algo_list')},
            },
        ),
        migrations.AddIndex(
            model_name='algooffer',
            index=models.Index(fields=['status', 'visibility'], name='core_algoof_status_a66a85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='algoplan',
            unique_together={('offer', 'name', 'period')},
        ),
        migrations.AddIndex(
            model_name='algoinvitation',
            index=models.Index(fields=['token'], name='core_algoin_token_430599_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='algosubscription',
            unique_together={('subscriber', 'offer')},
        ),
        migrations.AlterUniqueTogether(
            name='hiddenalgo',
            unique_together={('user', 'algo')},
        ),
    ]
