# Generated by Django 5.2.3 on 2025-08-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pendingsignup_pendingcontactchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('mic', models.CharField(blank=True, max_length=16)),
                ('segment_kind', models.CharField(blank=True, choices=[('EQ', 'Equity'), ('FO', 'F&O'), ('CDS', 'Currency'), ('COM', 'Commodity')], max_length=16)),
                ('default_xts_segment', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerExchangeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_code', models.CharField(max_length=32)),
                ('xts_segment', models.IntegerField(blank=True, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_maps', to='core.broker')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_maps', to='core.exchange')),
            ],
            options={
                'unique_together': {('broker', 'exchange')},
            },
        ),
    ]
