# Generated by Django 5.2.3 on 2025-08-26 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_exchange_brokerexchangemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmlogic',
            name='lot_qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='algorithmlogic',
            name='lot_size_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algorithmlogic',
            name='strike_kind',
            field=models.CharField(choices=[('ABS', 'Absolute'), ('ATM', 'ATM'), ('OTM', 'OTM')], default='ABS', max_length=8),
        ),
        migrations.AddField(
            model_name='algorithmlogic',
            name='strike_target',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='LegExecutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('resolved_symbol', models.CharField(max_length=100)),
                ('resolved_token', models.CharField(blank=True, max_length=32)),
                ('resolved_expiry', models.CharField(blank=True, max_length=20)),
                ('resolved_strike', models.CharField(blank=True, max_length=20)),
                ('lot_qty', models.PositiveIntegerField(default=1)),
                ('lot_size', models.PositiveIntegerField(default=0)),
                ('option_type', models.CharField(blank=True, max_length=10)),
                ('order_type', models.CharField(blank=True, max_length=20)),
                ('order_direction', models.CharField(blank=True, max_length=10)),
                ('filled_qty', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.algorithmlogic')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leg_snapshots', to='core.algorun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'leg', 'attempt'], name='core_legexe_run_id_cb3672_idx')],
            },
        ),
    ]
