# Generated by Django 5.2.3 on 2025-08-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_algorithmlogic_lot_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmlogic',
            name='exchange_segment',
            field=models.CharField(default='NFO', max_length=16),
        ),
    ]
