# Generated by Django 5.2.2 on 2025-08-27 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_algorithmlogic_exchange_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=36)),
                ('rule_type', models.CharField(max_length=20)),
                ('scope', models.CharField(max_length=20)),
                ('trigger_event', models.CharField(max_length=20)),
                ('priority', models.IntegerField(default=50)),
                ('condition_tree', models.JSONField(default=dict)),
                ('action_type', models.CharField(max_length=24)),
                ('action_params', models.JSONField(default=dict)),
                ('policy', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.algolist')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.algorithmlogic')),
            ],
            options={
                'indexes': [models.Index(fields=['algo', 'priority'], name='core_algoru_algo_id_3a527d_idx'), models.Index(fields=['algo', 'rule_type'], name='core_algoru_algo_id_396f87_idx')],
            },
        ),
    ]
