# Generated by Django 5.2.2 on 2025-08-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_algorule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmlogic',
            name='strike_kind',
            field=models.CharField(choices=[('ABS', 'Absolute'), ('ATM', 'ATM'), ('OTM', 'OTM')], default='ABS', max_length=20),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition_type',
            field=models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='condition',
            name='connector',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '=='), ('!=', '!=')], max_length=20),
        ),
        migrations.AlterField(
            model_name='condition',
            name='rhs_type',
            field=models.CharField(choices=[('value', 'Value'), ('variable', 'Variable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='legexecutionsnapshot',
            name='option_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
