# Generated by Django 5.2.2 on 2025-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_algorithmlogic_strike_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoinvitation',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='algooffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='algooffer',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='unlisted', max_length=20),
        ),
        migrations.AlterField(
            model_name='algoplan',
            name='period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='algorithmlogic',
            name='option_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='algorithmlogic',
            name='order_direction',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=20),
        ),
        migrations.AlterField(
            model_name='algorun',
            name='mode',
            field=models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], default='paper', max_length=20),
        ),
        migrations.AlterField(
            model_name='algorun',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error')], default='stopped', max_length=20),
        ),
        migrations.AlterField(
            model_name='algostatus',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='algosubscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailypnl',
            name='mode',
            field=models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], max_length=20),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='mode',
            field=models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], max_length=20),
        ),
        migrations.AlterField(
            model_name='legexecutionsnapshot',
            name='order_direction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('reset', 'Password Reset'), ('verify', 'Verify')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pendingcontactchange',
            name='field',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=20),
        ),
    ]
