# Generated by Django 5.2.2 on 2025-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_algoinvitation_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algolist',
            name='minimum_fund_reqd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
