"""
Django settings for Kuber project.

Generated by 'django-admin startproject' using Django 5.2.2.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# ----- Core env-driven settings -----
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-please-change")
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes")
_allowed = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()] or ["localhost", "127.0.0.1"]
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "TIMEOUT": 300,
    }
}

# Application definition
INSTALLED_APPS = [
    # Django defaults
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'widget_tweaks',            # (already there, helps in templates)
    'django_extensions',        # for shell_plus, graph_models, etc.
    'django.contrib.postgres',  # Postgres-specific fields (arrays, indexes, etc.)
    'channels',                 # WebSocket / async support (ties to Redis)

    # Your apps
    'core',
]


AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = 'Kuber.urls'

TEMPLATES = [{
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [BASE_DIR / "core" / "templates"],
    "APP_DIRS": True,
    "OPTIONS": {"context_processors": [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
    ]},
}]

WSGI_APPLICATION = "Kuber.wsgi.application"   # OK for HTTP; use Daphne later if you enable websockets



# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "kuber"),
        "USER": os.getenv("POSTGRES_USER", "kuber"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "kuber"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": int(os.getenv("POSTGRES_PORT", "5432")),
        "CONN_MAX_AGE": 60,
    }
}
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LOGIN_REDIRECT_URL = 'dashboard'  # or any named URL you want to land onafterlogin
LOGOUT_REDIRECT_URL = 'login'   # optional: where to go after logout


# Internationalization
APPEND_SLASH = True
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
RAZORPAY_WEBHOOK_SECRET = "..."
STRIPE_WEBHOOK_SECRET = "..."
USE_I18N = True
USE_TZ = True
ALLOWED_HOSTS = ['optionniti.com', 'www.optionniti.com','127.0.0.1','localhost']
# Razorpay
RAZORPAY_KEY_ID = "rzp_test_..."
RAZORPAY_KEY_SECRET = "..."
# Stripe
STRIPE_SECRET_KEY = "sk_live_..."
CHECKOUT_SUCCESS_URL = "https://www.optionniti.com/billing/success"
CHECKOUT_CANCEL_URL  = "https://www.optionniti.com/billing/cancel"

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / 'core' / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


